[docker]
configs = [
    "selenium/standalone-firefox:4.2.2-20220609", "{\"browserName\": \"firefox\"}",
    "selenium/standalone-chrome:4.2.2-20220609", "{\"browserName\": \"chrome\"}",
    "selenium/standalone-edge:4.2.2-20220609", "{\"browserName\": \"MicrosoftEdge\"}"
]
url = "http://127.0.0.1:2375"
# Docker image used for video recording
video-image = "selenium/video:ffmpeg-4.3.1-20220609"